services:
  frontend:
    build:
      context: ./frontend
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      SPRING_REST_API_URL: http://springboot-app:8080/api
      NEXTAUTH_URL: http://nextjs-app:3000
      NEXTAUTH_SECRET: WVBoRUhRdVZsT25YcUpkTGFmam9iVHRlQVNSeml3SURaTkNNS3NGVw==
      NEXT_PUBLIC_URL: http://nextjs-app:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dendaiTech
      SPRING_DATASOURCE_USERNAME: kaihatsurta
      SPRING_DATASOURCE_PASSWORD: WEVtaE1pVkFwc0NuRkJkUVp1dmM
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: dendaiTech
      POSTGRES_USER: kaihatsurta
      POSTGRES_PASSWORD: WEVtaE1pVkFwc0NuRkJkUVp1dmM
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d # SQLスクリプトを自動実行するための設定
    ports:
      - "54320:5432"

volumes:
  db-data:
