spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://db:5432/dendaiTech
    username: kaihatsurta
    password: WEVtaE1pVkFwc0NuRkJkUVp1dmM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      zaxxer:
        hikari: DEBUG

jwt:
  secret: ZC0e9PI+xuOgwryN5csYNd1+hbHo1iiz05JsTemKc70=
  expiration: 3600


registration:
  common:
    password:
      admin: adminCommonPass123
      student: studentCommonPass789