name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: .ssh/dendaiGit
          host: 133.20.51.166
          username: wsp
          port: 22
          script: |
            cd conoha-app
            git pull origin main     
